name: fl_caption
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^3.0.0
  json_annotation: ^4.9.0
  flutter_rust_bridge: ^2.7.1
  fluent_ui: ^4.12.0
  freezed_annotation: ^3.1.0
  visibility_detector: ^0.4.0+2
  rust_lib_fl_caption:
    path: rust_builder

  # Desktop window tools
  bitsdojo_window: ^0.1.6
  window_manager: ^0.5.1
  flutter_acrylic: ^1.1.4
  desktop_multi_window: ^0.2.1

  # KV Store
  hive_ce: ^2.11.4
  hive_ce_flutter: ^2.3.2

  # local store
  path_provider: ^2.1.5

  # Network
  dio: ^5.9.0
  dio_compatibility_layer: ^0.1.0
  rhttp: ^0.13.0

  # Async lock
  synchronized: ^3.4.0

  # UI components
  super_sliver_list: ^0.4.1

  # Icons
  font_awesome_flutter: ^10.10.0

  # Platform Tools
  file_picker: ^10.3.2

  url_launcher: ^6.3.2

dependency_overrides: 
  macos_window_utils: 1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.12
  build_runner: ^2.7.1
  freezed: ^3.2.0
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.0-dev.17
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0-dev.17
  ffigen: ^19.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/whisper/
    - assets/whisper/onnx/
    - assets/models/
  fonts:
    - family: SourceHanSansCN-Regular
      fonts:
        - asset: assets/SourceHanSansCN-Regular.otf