// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../whisper_caption/whisper.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> createCancellationToken() =>
    RustLib.instance.api.crateApiWhisperCreateCancellationToken();

Future<void> cancelCancellationToken({required String tokenId}) => RustLib
    .instance
    .api
    .crateApiWhisperCancelCancellationToken(tokenId: tokenId);

Stream<List<Segment>> launchCaption({
  required WhisperClient whisperClient,
  String? audioDevice,
  bool? audioDeviceIsInput,
  String? audioLanguage,
  required String cancelTokenId,
  bool? withTimestamps,
  bool? verbose,
  bool? tryWithCuda,
  int? whisperMaxAudioDuration,
  BigInt? inferenceInterval,
  BigInt? whisperDefaultMaxDecodeTokens,
  double? whisperTemperature,
}) => RustLib.instance.api.crateApiWhisperLaunchCaption(
  whisperClient: whisperClient,
  audioDevice: audioDevice,
  audioDeviceIsInput: audioDeviceIsInput,
  audioLanguage: audioLanguage,
  cancelTokenId: cancelTokenId,
  withTimestamps: withTimestamps,
  verbose: verbose,
  tryWithCuda: tryWithCuda,
  whisperMaxAudioDuration: whisperMaxAudioDuration,
  inferenceInterval: inferenceInterval,
  whisperDefaultMaxDecodeTokens: whisperDefaultMaxDecodeTokens,
  whisperTemperature: whisperTemperature,
);

class WhisperClient {
  final String whisperModel;
  final String whisperConfig;
  final Uint8List whisperTokenizer;
  final bool isMultilingual;
  final bool isQuantized;

  const WhisperClient({
    required this.whisperModel,
    required this.whisperConfig,
    required this.whisperTokenizer,
    required this.isMultilingual,
    required this.isQuantized,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WhisperClient> newInstance({
    required String whisperModel,
    required String whisperConfig,
    required List<int> whisperTokenizer,
    required bool isMultilingual,
    required bool isQuantized,
  }) => RustLib.instance.api.crateApiWhisperWhisperClientNew(
    whisperModel: whisperModel,
    whisperConfig: whisperConfig,
    whisperTokenizer: whisperTokenizer,
    isMultilingual: isMultilingual,
    isQuantized: isQuantized,
  );

  @override
  int get hashCode =>
      whisperModel.hashCode ^
      whisperConfig.hashCode ^
      whisperTokenizer.hashCode ^
      isMultilingual.hashCode ^
      isQuantized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WhisperClient &&
          runtimeType == other.runtimeType &&
          whisperModel == other.whisperModel &&
          whisperConfig == other.whisperConfig &&
          whisperTokenizer == other.whisperTokenizer &&
          isMultilingual == other.isMultilingual &&
          isQuantized == other.isQuantized;
}
