// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/whisper.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'whisper_caption/whisper.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.9.0';

  @override
  int get rustContentHash => 789492351;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_fl_caption',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiWhisperCancelCancellationToken({
    required String tokenId,
  });

  Future<String> crateApiWhisperCreateCancellationToken();

  Stream<List<Segment>> crateApiWhisperLaunchCaption({
    required WhisperClient whisperClient,
    String? audioDevice,
    bool? audioDeviceIsInput,
    String? audioLanguage,
    required String cancelTokenId,
    bool? withTimestamps,
    bool? verbose,
    bool? tryWithCuda,
  });

  Future<WhisperClient> crateApiWhisperWhisperClientNew({
    required String whisperModel,
    required String whisperConfig,
    required List<int> whisperTokenizer,
    required bool isMultilingual,
    required bool isQuantized,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiWhisperCancelCancellationToken({
    required String tokenId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(tokenId);
          return wire.wire__crate__api__whisper__cancel_cancellation_token(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperCancelCancellationTokenConstMeta,
        argValues: [tokenId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperCancelCancellationTokenConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_cancellation_token",
        argNames: ["tokenId"],
      );

  @override
  Future<String> crateApiWhisperCreateCancellationToken() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__whisper__create_cancellation_token(
            port_,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperCreateCancellationTokenConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperCreateCancellationTokenConstMeta =>
      const TaskConstMeta(debugName: "create_cancellation_token", argNames: []);

  @override
  Stream<List<Segment>> crateApiWhisperLaunchCaption({
    required WhisperClient whisperClient,
    String? audioDevice,
    bool? audioDeviceIsInput,
    String? audioLanguage,
    required String cancelTokenId,
    bool? withTimestamps,
    bool? verbose,
    bool? tryWithCuda,
  }) {
    final streamSink = RustStreamSink<List<Segment>>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            var arg0 = cst_encode_box_autoadd_whisper_client(whisperClient);
            var arg1 = cst_encode_StreamSink_list_segment_Dco(streamSink);
            var arg2 = cst_encode_opt_String(audioDevice);
            var arg3 = cst_encode_opt_box_autoadd_bool(audioDeviceIsInput);
            var arg4 = cst_encode_opt_String(audioLanguage);
            var arg5 = cst_encode_String(cancelTokenId);
            var arg6 = cst_encode_opt_box_autoadd_bool(withTimestamps);
            var arg7 = cst_encode_opt_box_autoadd_bool(verbose);
            var arg8 = cst_encode_opt_box_autoadd_bool(tryWithCuda);
            return wire.wire__crate__api__whisper__launch_caption(
              port_,
              arg0,
              arg1,
              arg2,
              arg3,
              arg4,
              arg5,
              arg6,
              arg7,
              arg8,
            );
          },
          codec: DcoCodec(
            decodeSuccessData: dco_decode_unit,
            decodeErrorData: dco_decode_AnyhowException,
          ),
          constMeta: kCrateApiWhisperLaunchCaptionConstMeta,
          argValues: [
            whisperClient,
            streamSink,
            audioDevice,
            audioDeviceIsInput,
            audioLanguage,
            cancelTokenId,
            withTimestamps,
            verbose,
            tryWithCuda,
          ],
          apiImpl: this,
        ),
      ),
    );
    return streamSink.stream;
  }

  TaskConstMeta get kCrateApiWhisperLaunchCaptionConstMeta =>
      const TaskConstMeta(
        debugName: "launch_caption",
        argNames: [
          "whisperClient",
          "streamSink",
          "audioDevice",
          "audioDeviceIsInput",
          "audioLanguage",
          "cancelTokenId",
          "withTimestamps",
          "verbose",
          "tryWithCuda",
        ],
      );

  @override
  Future<WhisperClient> crateApiWhisperWhisperClientNew({
    required String whisperModel,
    required String whisperConfig,
    required List<int> whisperTokenizer,
    required bool isMultilingual,
    required bool isQuantized,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(whisperModel);
          var arg1 = cst_encode_String(whisperConfig);
          var arg2 = cst_encode_list_prim_u_8_loose(whisperTokenizer);
          var arg3 = cst_encode_bool(isMultilingual);
          var arg4 = cst_encode_bool(isQuantized);
          return wire.wire__crate__api__whisper__whisper_client_new(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_whisper_client,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperWhisperClientNewConstMeta,
        argValues: [
          whisperModel,
          whisperConfig,
          whisperTokenizer,
          isMultilingual,
          isQuantized,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperWhisperClientNewConstMeta =>
      const TaskConstMeta(
        debugName: "whisper_client_new",
        argNames: [
          "whisperModel",
          "whisperConfig",
          "whisperTokenizer",
          "isMultilingual",
          "isQuantized",
        ],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<List<Segment>> dco_decode_StreamSink_list_segment_Dco(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BigInt dco_decode_U128(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BigInt.parse(raw);
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  WhisperClient dco_decode_box_autoadd_whisper_client(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_whisper_client(raw);
  }

  @protected
  DecodingResult dco_decode_decoding_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return DecodingResult(
      tokens: dco_decode_list_prim_u_32_strict(arr[0]),
      text: dco_decode_String(arr[1]),
      avgLogprob: dco_decode_f_64(arr[2]),
      noSpeechProb: dco_decode_f_64(arr[3]),
      temperature: dco_decode_f_64(arr[4]),
      compressionRatio: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Segment> dco_decode_list_segment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_segment).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_U128(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_U128(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  Segment dco_decode_segment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Segment(
      start: dco_decode_f_64(arr[0]),
      duration: dco_decode_f_64(arr[1]),
      dr: dco_decode_decoding_result(arr[2]),
      reasoningDuration: dco_decode_opt_U128(arr[3]),
      reasoningLang: dco_decode_opt_String(arr[4]),
      audioDuration: dco_decode_opt_U128(arr[5]),
      status: dco_decode_whisper_status(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WhisperClient dco_decode_whisper_client(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return WhisperClient(
      whisperModel: dco_decode_String(arr[0]),
      whisperConfig: dco_decode_String(arr[1]),
      whisperTokenizer: dco_decode_list_prim_u_8_strict(arr[2]),
      isMultilingual: dco_decode_bool(arr[3]),
      isQuantized: dco_decode_bool(arr[4]),
    );
  }

  @protected
  WhisperStatus dco_decode_whisper_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WhisperStatus.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<List<Segment>> sse_decode_StreamSink_list_segment_Dco(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BigInt sse_decode_U128(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return BigInt.parse(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  WhisperClient sse_decode_box_autoadd_whisper_client(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_whisper_client(deserializer));
  }

  @protected
  DecodingResult sse_decode_decoding_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tokens = sse_decode_list_prim_u_32_strict(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_avgLogprob = sse_decode_f_64(deserializer);
    var var_noSpeechProb = sse_decode_f_64(deserializer);
    var var_temperature = sse_decode_f_64(deserializer);
    var var_compressionRatio = sse_decode_f_64(deserializer);
    return DecodingResult(
      tokens: var_tokens,
      text: var_text,
      avgLogprob: var_avgLogprob,
      noSpeechProb: var_noSpeechProb,
      temperature: var_temperature,
      compressionRatio: var_compressionRatio,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Segment> sse_decode_list_segment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Segment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_segment(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_U128(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_U128(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Segment sse_decode_segment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_start = sse_decode_f_64(deserializer);
    var var_duration = sse_decode_f_64(deserializer);
    var var_dr = sse_decode_decoding_result(deserializer);
    var var_reasoningDuration = sse_decode_opt_U128(deserializer);
    var var_reasoningLang = sse_decode_opt_String(deserializer);
    var var_audioDuration = sse_decode_opt_U128(deserializer);
    var var_status = sse_decode_whisper_status(deserializer);
    return Segment(
      start: var_start,
      duration: var_duration,
      dr: var_dr,
      reasoningDuration: var_reasoningDuration,
      reasoningLang: var_reasoningLang,
      audioDuration: var_audioDuration,
      status: var_status,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WhisperClient sse_decode_whisper_client(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_whisperModel = sse_decode_String(deserializer);
    var var_whisperConfig = sse_decode_String(deserializer);
    var var_whisperTokenizer = sse_decode_list_prim_u_8_strict(deserializer);
    var var_isMultilingual = sse_decode_bool(deserializer);
    var var_isQuantized = sse_decode_bool(deserializer);
    return WhisperClient(
      whisperModel: var_whisperModel,
      whisperConfig: var_whisperConfig,
      whisperTokenizer: var_whisperTokenizer,
      isMultilingual: var_isMultilingual,
      isQuantized: var_isQuantized,
    );
  }

  @protected
  WhisperStatus sse_decode_whisper_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return WhisperStatus.values[inner];
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  double cst_encode_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_whisper_status(WhisperStatus raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_list_segment_Dco(
    RustStreamSink<List<Segment>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_segment,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_U128(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.toString(), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_whisper_client(
    WhisperClient self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_whisper_client(self, serializer);
  }

  @protected
  void sse_encode_decoding_result(
    DecodingResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_32_strict(self.tokens, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_f_64(self.avgLogprob, serializer);
    sse_encode_f_64(self.noSpeechProb, serializer);
    sse_encode_f_64(self.temperature, serializer);
    sse_encode_f_64(self.compressionRatio, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_segment(List<Segment> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_segment(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_U128(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_U128(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_segment(Segment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.start, serializer);
    sse_encode_f_64(self.duration, serializer);
    sse_encode_decoding_result(self.dr, serializer);
    sse_encode_opt_U128(self.reasoningDuration, serializer);
    sse_encode_opt_String(self.reasoningLang, serializer);
    sse_encode_opt_U128(self.audioDuration, serializer);
    sse_encode_whisper_status(self.status, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_whisper_client(WhisperClient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.whisperModel, serializer);
    sse_encode_String(self.whisperConfig, serializer);
    sse_encode_list_prim_u_8_strict(self.whisperTokenizer, serializer);
    sse_encode_bool(self.isMultilingual, serializer);
    sse_encode_bool(self.isQuantized, serializer);
  }

  @protected
  void sse_encode_whisper_status(WhisperStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
