// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/whisper.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'whisper_caption/whisper.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CancellationTokenPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationTokenPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  CancellationToken
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
    dynamic raw,
  );

  @protected
  CancellationToken
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<Segment>> dco_decode_StreamSink_list_segment_Dco(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  WhisperClient dco_decode_box_autoadd_whisper_client(dynamic raw);

  @protected
  DecodingResult dco_decode_decoding_result(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Segment> dco_decode_list_segment(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  Segment dco_decode_segment(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WhisperClient dco_decode_whisper_client(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  CancellationToken
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
    SseDeserializer deserializer,
  );

  @protected
  CancellationToken
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<Segment>> sse_decode_StreamSink_list_segment_Dco(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  WhisperClient sse_decode_box_autoadd_whisper_client(
    SseDeserializer deserializer,
  );

  @protected
  DecodingResult sse_decode_decoding_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Segment> sse_decode_list_segment(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  Segment sse_decode_segment(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WhisperClient sse_decode_whisper_client(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
    AnyhowException raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
  cst_encode_StreamSink_list_segment_Dco(RustStreamSink<List<Segment>> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_segment,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Bool> cst_encode_box_autoadd_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_bool(cst_encode_bool(raw));
  }

  @protected
  ffi.Pointer<wire_cst_whisper_client> cst_encode_box_autoadd_whisper_client(
    WhisperClient raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_whisper_client();
    cst_api_fill_to_wire_whisper_client(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_32_strict> cst_encode_list_prim_u_32_strict(
    Uint32List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_32_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
    List<int> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_segment> cst_encode_list_segment(
    List<Segment> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_segment(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_segment(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Bool> cst_encode_opt_box_autoadd_bool(bool? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_bool(raw);
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_whisper_client(
    WhisperClient apiObj,
    ffi.Pointer<wire_cst_whisper_client> wireObj,
  ) {
    cst_api_fill_to_wire_whisper_client(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_decoding_result(
    DecodingResult apiObj,
    wire_cst_decoding_result wireObj,
  ) {
    wireObj.tokens = cst_encode_list_prim_u_32_strict(apiObj.tokens);
    wireObj.text = cst_encode_String(apiObj.text);
    wireObj.avg_logprob = cst_encode_f_64(apiObj.avgLogprob);
    wireObj.no_speech_prob = cst_encode_f_64(apiObj.noSpeechProb);
    wireObj.temperature = cst_encode_f_64(apiObj.temperature);
    wireObj.compression_ratio = cst_encode_f_64(apiObj.compressionRatio);
  }

  @protected
  void cst_api_fill_to_wire_segment(Segment apiObj, wire_cst_segment wireObj) {
    wireObj.start = cst_encode_f_64(apiObj.start);
    wireObj.duration = cst_encode_f_64(apiObj.duration);
    cst_api_fill_to_wire_decoding_result(apiObj.dr, wireObj.dr);
  }

  @protected
  void cst_api_fill_to_wire_whisper_client(
    WhisperClient apiObj,
    wire_cst_whisper_client wireObj,
  ) {
    wireObj.whisper_model = cst_encode_String(apiObj.whisperModel);
    wireObj.whisper_config = cst_encode_String(apiObj.whisperConfig);
    wireObj.whisper_tokenizer = cst_encode_list_prim_u_8_strict(
      apiObj.whisperTokenizer,
    );
    wireObj.is_multilingual = cst_encode_bool(apiObj.isMultilingual);
    wireObj.is_quantized = cst_encode_bool(apiObj.isQuantized);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
    CancellationToken raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
    CancellationToken raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
    CancellationToken self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
    CancellationToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_segment_Dco(
    RustStreamSink<List<Segment>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_whisper_client(
    WhisperClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_decoding_result(
    DecodingResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_segment(List<Segment> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_segment(Segment self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_whisper_client(WhisperClient self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject =
      _store_dart_post_cobjectPtr
          .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__whisper__cancel_cancellation_token(
    int port_,
    int token,
  ) {
    return _wire__crate__api__whisper__cancel_cancellation_token(port_, token);
  }

  late final _wire__crate__api__whisper__cancel_cancellation_tokenPtr = _lookup<
    ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>
  >('frbgen_fl_caption_wire__crate__api__whisper__cancel_cancellation_token');
  late final _wire__crate__api__whisper__cancel_cancellation_token =
      _wire__crate__api__whisper__cancel_cancellation_tokenPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__whisper__create_cancellation_token(int port_) {
    return _wire__crate__api__whisper__create_cancellation_token(port_);
  }

  late final _wire__crate__api__whisper__create_cancellation_tokenPtr = _lookup<
    ffi.NativeFunction<ffi.Void Function(ffi.Int64)>
  >('frbgen_fl_caption_wire__crate__api__whisper__create_cancellation_token');
  late final _wire__crate__api__whisper__create_cancellation_token =
      _wire__crate__api__whisper__create_cancellation_tokenPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__whisper__launch_caption(
    int port_,
    ffi.Pointer<wire_cst_whisper_client> whisper_client,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> stream_sink,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> audio_device,
    ffi.Pointer<ffi.Bool> audio_device_is_input,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> audio_language,
    int cancel_token,
    ffi.Pointer<ffi.Bool> with_timestamps,
    ffi.Pointer<ffi.Bool> verbose,
  ) {
    return _wire__crate__api__whisper__launch_caption(
      port_,
      whisper_client,
      stream_sink,
      audio_device,
      audio_device_is_input,
      audio_language,
      cancel_token,
      with_timestamps,
      verbose,
    );
  }

  late final _wire__crate__api__whisper__launch_captionPtr = _lookup<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Int64,
        ffi.Pointer<wire_cst_whisper_client>,
        ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        ffi.Pointer<ffi.Bool>,
        ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        ffi.UintPtr,
        ffi.Pointer<ffi.Bool>,
        ffi.Pointer<ffi.Bool>,
      )
    >
  >('frbgen_fl_caption_wire__crate__api__whisper__launch_caption');
  late final _wire__crate__api__whisper__launch_caption =
      _wire__crate__api__whisper__launch_captionPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_whisper_client>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.Bool>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              ffi.Pointer<ffi.Bool>,
              ffi.Pointer<ffi.Bool>,
            )
          >();

  void wire__crate__api__whisper__whisper_client_new(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> whisper_model,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> whisper_config,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> whisper_tokenizer,
    bool is_multilingual,
    bool is_quantized,
  ) {
    return _wire__crate__api__whisper__whisper_client_new(
      port_,
      whisper_model,
      whisper_config,
      whisper_tokenizer,
      is_multilingual,
      is_quantized,
    );
  }

  late final _wire__crate__api__whisper__whisper_client_newPtr = _lookup<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Int64,
        ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        ffi.Pointer<wire_cst_list_prim_u_8_loose>,
        ffi.Bool,
        ffi.Bool,
      )
    >
  >('frbgen_fl_caption_wire__crate__api__whisper__whisper_client_new');
  late final _wire__crate__api__whisper__whisper_client_new =
      _wire__crate__api__whisper__whisper_client_newPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_loose>,
              bool,
              bool,
            )
          >();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationTokenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_fl_caption_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationTokenPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationTokenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_fl_caption_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationToken =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCancellationTokenPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Bool> cst_new_box_autoadd_bool(bool value) {
    return _cst_new_box_autoadd_bool(value);
  }

  late final _cst_new_box_autoadd_boolPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Bool> Function(ffi.Bool)>>(
        'frbgen_fl_caption_cst_new_box_autoadd_bool',
      );
  late final _cst_new_box_autoadd_bool =
      _cst_new_box_autoadd_boolPtr
          .asFunction<ffi.Pointer<ffi.Bool> Function(bool)>();

  ffi.Pointer<wire_cst_whisper_client> cst_new_box_autoadd_whisper_client() {
    return _cst_new_box_autoadd_whisper_client();
  }

  late final _cst_new_box_autoadd_whisper_clientPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<wire_cst_whisper_client> Function()>
  >('frbgen_fl_caption_cst_new_box_autoadd_whisper_client');
  late final _cst_new_box_autoadd_whisper_client =
      _cst_new_box_autoadd_whisper_clientPtr
          .asFunction<ffi.Pointer<wire_cst_whisper_client> Function()>();

  ffi.Pointer<wire_cst_list_prim_u_32_strict> cst_new_list_prim_u_32_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_32_strict(len);
  }

  late final _cst_new_list_prim_u_32_strictPtr = _lookup<
    ffi.NativeFunction<
      ffi.Pointer<wire_cst_list_prim_u_32_strict> Function(ffi.Int32)
    >
  >('frbgen_fl_caption_cst_new_list_prim_u_32_strict');
  late final _cst_new_list_prim_u_32_strict =
      _cst_new_list_prim_u_32_strictPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_prim_u_32_strict> Function(int)
          >();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr = _lookup<
    ffi.NativeFunction<
      ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(ffi.Int32)
    >
  >('frbgen_fl_caption_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose =
      _cst_new_list_prim_u_8_loosePtr
          .asFunction<
            ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)
          >();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
    ffi.NativeFunction<
      ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
    >
  >('frbgen_fl_caption_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict =
      _cst_new_list_prim_u_8_strictPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)
          >();

  ffi.Pointer<wire_cst_list_segment> cst_new_list_segment(int len) {
    return _cst_new_list_segment(len);
  }

  late final _cst_new_list_segmentPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<wire_cst_list_segment> Function(ffi.Int32)>
  >('frbgen_fl_caption_cst_new_list_segment');
  late final _cst_new_list_segment =
      _cst_new_list_segmentPtr
          .asFunction<ffi.Pointer<wire_cst_list_segment> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_whisper_client extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> whisper_model;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> whisper_config;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> whisper_tokenizer;

  @ffi.Bool()
  external bool is_multilingual;

  @ffi.Bool()
  external bool is_quantized;
}

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_32_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint32> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_decoding_result extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_32_strict> tokens;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> text;

  @ffi.Double()
  external double avg_logprob;

  @ffi.Double()
  external double no_speech_prob;

  @ffi.Double()
  external double temperature;

  @ffi.Double()
  external double compression_ratio;
}

final class wire_cst_segment extends ffi.Struct {
  @ffi.Double()
  external double start;

  @ffi.Double()
  external double duration;

  external wire_cst_decoding_result dr;
}

final class wire_cst_list_segment extends ffi.Struct {
  external ffi.Pointer<wire_cst_segment> ptr;

  @ffi.Int32()
  external int len;
}
