[package]
name = "rust_lib_fl_caption"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.1"
tokio = { version = "1.44.0", features = ["full"] }
tokio-util = "0.7.13"
anyhow = "1.0"
candle-core = "0.8.3"
candle-nn = "0.8.3"
candle-transformers = "0.8.3"
tokenizers = "0.21.0"
serde_json = "1.0.140"
rand = "0.9.0"
rand_distr = "0.5.1"
cpal = "0.15.2"
byteorder = "1.5.0"
rubato = "0.16.1"
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
