[package]
name = "rust_lib_fl_caption"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.1"
tokio = { version = "1.44.0", features = ["full"] }
tokio-util = "0.7.13"
anyhow = "1.0"
candle-core = { version = "0.8.3", features = ["cuda"] }
candle-nn = { version = "0.8.3", features = ["cuda"] }
candle-transformers = { version = "0.8.3", features = ["cuda"] }
tokenizers = "0.21.0"
serde_json = "1.0.140"
rand = "0.9.0"
rand_distr = "0.5.1"
cpal = "0.15.2"
byteorder = "1.5.0"
rubato = "0.16.1"
once_cell = "1.18.0"
uuid = { version = "1.4.1", features = ["v4"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
