name: "macOS Build"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Protoc
        uses: arduino/setup-protoc@v3
      
      - name: Check System Information
        run: |
          echo "User: $USER"
          echo "Date: $(date '+%Y-%m-%d %H:%M:%S')"
          echo "========== System Information =========="
          uname -a
          echo "Xcode Command Line Tools:"
          xcode-select --print-path
          echo "Available Xcode versions:"
          ls -la /Applications/Xcode*.app 2>/dev/null || echo "No Xcode apps found"
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
      - run: flutter --version

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Version
        run: |
          rustup --version  
          cargo --version
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust"
          cache-all-crates: true

      - name: Set up LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18"

      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter build runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Rust cargo update
        run: cargo update
        working-directory: rust

      - name: Set up Flutter rust bridge
        run: |
          cargo install cargo-expand 
          cargo install 'flutter_rust_bridge_codegen'
      - name: Flutter Rust bridge generate
        run: flutter_rust_bridge_codegen generate
      #      - name: flutter gen l10n
      #        run: |
      #          flutter pub global activate intl_utils
      #          flutter pub global run intl_utils:generate
   
      - name: Flutter Build
        run: |
          flutter build macos -v

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: build/macos/Build/Products/Release
